//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.12 at 08:20:34 PM EEST 
//


package com.xmlproject.model;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="statistics"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dateTimeOfCreation" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="applicationClassName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="chapters" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="paragraphs" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="lines" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="distinctWords" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="allWords" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="chapter" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="paragraph" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statistics",
    "chapter"
})
@XmlRootElement(name = "book", namespace="https://www.w3schools.com")
public class Book {

    @XmlElement(required = true)
    protected Book.Statistics statistics;
    protected List<Book.Chapter> chapter;

    public Book(Statistics statistics, List<Chapter> chapter) {
        this.statistics = statistics;
        this.chapter = chapter;
    }

    @Override
    public String toString() {
        return "Book{" +
                "statistics=" + statistics +
                '}';
    }

    public Book() {
    }

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link Book.Statistics }
     *     
     */
    public Book.Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Book.Statistics }
     *     
     */
    public void setStatistics(Book.Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the chapter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chapter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChapter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Book.Chapter }
     * 
     * 
     */
    public List<Book.Chapter> getChapter() {
        if (chapter == null) {
            chapter = new ArrayList<Book.Chapter>();
        }
        return this.chapter;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="paragraph" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paragraph"
    })
    public static class Chapter {

        protected List<Book.Chapter.Paragraph> paragraph;
        @XmlAttribute(name = "id")
        protected BigInteger id;

        /**
         * Gets the value of the paragraph property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paragraph property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParagraph().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Book.Chapter.Paragraph }
         * 
         * 
         */
        public List<Book.Chapter.Paragraph> getParagraph() {
            if (paragraph == null) {
                paragraph = new ArrayList<Book.Chapter.Paragraph>();
            }
            return this.paragraph;
        }

        public Chapter(List<Paragraph> paragraph, BigInteger id) {
            this.paragraph = paragraph;
            this.id = id;
        }

        public Chapter() {
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "line"
        })
        public static class Paragraph {

            protected List<String> line;
            @XmlAttribute(name = "id")
            protected BigInteger id;

            /**
             * Gets the value of the line property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the line property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getLine() {
                if (line == null) {
                    line = new ArrayList<String>();
                }
                return this.line;
            }

            public Paragraph() {
            }

            public Paragraph(List<String> line, BigInteger id) {
                this.line = line;
                this.id = id;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setId(BigInteger value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="dateTimeOfCreation" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="applicationClassName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="chapters" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="paragraphs" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="lines" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="distinctWords" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="allWords" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateTimeOfCreation",
        "author",
        "applicationClassName",
        "chapters",
        "paragraphs",
        "lines",
        "distinctWords",
        "allWords"
    })
    public static class Statistics {

        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dateTimeOfCreation;
        @XmlElement(required = true)
        protected String author;
        @XmlElement(required = true)
        protected String applicationClassName;
        protected byte chapters;
        protected short paragraphs;
        protected int lines;
        protected short distinctWords;
        protected int allWords;

        public Statistics() {
        }

        @Override
        public String toString() {
            return "Statistics{" +
                    "dateTimeOfCreation=" + dateTimeOfCreation +
                    ", author='" + author + '\'' +
                    ", applicationClassName='" + applicationClassName + '\'' +
                    ", chapters=" + chapters +
                    ", paragraphs=" + paragraphs +
                    ", lines=" + lines +
                    ", distinctWords=" + distinctWords +
                    ", allWords=" + allWords +
                    '}';
        }

        public Statistics(XMLGregorianCalendar dateTimeOfCreation, String author, String applicationClassName, byte chapters, short paragraphs, int lines, short distinctWords, int allWords) {
            this.dateTimeOfCreation = dateTimeOfCreation;
            this.author = author;
            this.applicationClassName = applicationClassName;
            this.chapters = chapters;
            this.paragraphs = paragraphs;
            this.lines = lines;
            this.distinctWords = distinctWords;
            this.allWords = allWords;
        }

        /**
         * Gets the value of the dateTimeOfCreation property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateTimeOfCreation() {
            return dateTimeOfCreation;
        }

        /**
         * Sets the value of the dateTimeOfCreation property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateTimeOfCreation(XMLGregorianCalendar value) {
            this.dateTimeOfCreation = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the applicationClassName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationClassName() {
            return applicationClassName;
        }

        /**
         * Sets the value of the applicationClassName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationClassName(String value) {
            this.applicationClassName = value;
        }

        /**
         * Gets the value of the chapters property.
         * 
         */
        public byte getChapters() {
            return chapters;
        }

        /**
         * Sets the value of the chapters property.
         * 
         */
        public void setChapters(byte value) {
            this.chapters = value;
        }

        /**
         * Gets the value of the paragraphs property.
         * 
         */
        public short getParagraphs() {
            return paragraphs;
        }

        /**
         * Sets the value of the paragraphs property.
         * 
         */
        public void setParagraphs(short value) {
            this.paragraphs = value;
        }

        /**
         * Gets the value of the lines property.
         * 
         */
        public int getLines() {
            return lines;
        }

        /**
         * Sets the value of the lines property.
         * 
         */
        public void setLines(int value) {
            this.lines = value;
        }

        /**
         * Gets the value of the distinctWords property.
         * 
         */
        public short getDistinctWords() {
            return distinctWords;
        }

        /**
         * Sets the value of the distinctWords property.
         * 
         */
        public void setDistinctWords(short value) {
            this.distinctWords = value;
        }

        /**
         * Gets the value of the allWords property.
         * 
         */
        public int getAllWords() {
            return allWords;
        }

        /**
         * Sets the value of the allWords property.
         * 
         */
        public void setAllWords(int value) {
            this.allWords = value;
        }

    }

}
