//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.12 at 08:20:34 PM EEST 
//


package com.xmlproject.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_w3schools package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_w3schools
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Book.Chapter }
     * 
     */
    public Book.Chapter createBookChapter() {
        return new Book.Chapter();
    }

    /**
     * Create an instance of {@link Book.Statistics }
     * 
     */
    public Book.Statistics createBookStatistics() {
        return new Book.Statistics();
    }

    /**
     * Create an instance of {@link Book.Chapter.Paragraph }
     * 
     */
    public Book.Chapter.Paragraph createBookChapterParagraph() {
        return new Book.Chapter.Paragraph();
    }

}
