//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.12 at 08:20:34 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.w3schools.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = @XmlNs(prefix = "", namespaceURI = "https://www.w3schools.com"))
package com.xmlproject.model;

import javax.xml.bind.annotation.XmlNs;